name: Todo App CI/CD Pipeline

on:
  push:
    branches: [main]


jobs:
    build:
      name: Build Phase
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 20
            cache: 'npm'

        - name: Install dependencies
          run: npm install

        - name: Build application
          run: npm run build

        - name: Upload build artifacts
          uses: actions/upload-artifact@v4
          with:
            name: build-files
            path: dist/
            retention-days: 1

    test:
      name: Test Phase
      runs-on: ubuntu-latest
      needs: build

      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 20
            cache: 'npm'

        - name: Install dependencies
          run: npm install

        - name: Run tests
          run: npm run test 
    deploy: 
      name: Deploy Phase
      runs-on: ubuntu-latest
      needs: [build, test]

      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 20
            cache: 'npm'

        - name: Download build artifacts
          uses: actions/download-artifact@v4
          with:
            name: build-files
            path: dist/

        - name: Install Firebase CLI
          run: npm install -g firebase-tools

        - name: Install dependencies
          run: npm install

        - name: Prepare Google Application Credentials
          run: | 
            echo ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }} | base64 --decode > HOME/private_key.json  
            
        - name: Deploy Firebase
          run: |
           export GOOGLE_APPLICATION_CREDENTIALS= "$HOME/private_key.json"
           firebase experiments:enable webframeworks
           forebase deploy --only hosting

        - name: Remove private key
          if: always()
          run: rm $HOME/private_key.json