name: Todo App CI/CD Pipeline

on:
  push:
    branches: [main]
  
  jobs:
    build:
      name: Build Phase
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 20
            cache: 'npm'

        - name: Install dependencies
          run: npm install

        - name: Build application
          run: npm run build

        - name: Upload build artifacts
          uses: actions/upload-artifact@v4
          with:
            name: build-files
            pathh: dist/
            retention-days: 1

    test:
      name: Test Phase
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 20
            cache: 'npm'

        - name: Install dependencies
          run: npm install

        - name: Run tests
          run: npm run test        